#!/bin/bash

SRC_VERSION="4.2"
SRC_FILENAME="bash-$SRC_VERSION.tgz"
SRC_FETCH_PATH="http://ftp.gnu.org/gnu/bash/bash-$SRC_VERSION.tar.gz"
SRC_FETCH_METHOD="http"
PATCHES=( bash42-{001..045} )

set -e
if [[ ! -e ../$SRC_FILENAME ]] ; then
    if ! curl -L -s -o "../$SRC_FILENAME" "$SRC_FETCH_PATH" ; then
        die "can't read or download $SRC_FILENAME"
    fi
fi
tar zxf ../$SRC_FILENAME --strip-components 1 -C $BUILDDIR
for patch in ${PATCHES[@]} ; do
  patch -p0 < $PDIR/$patch
done

./configure --prefix="/usr" --sysconfdir="/etc"
make
strip bash

if [[ -d $DESTDIR ]] ; then
  cp bash $DESTDIR/$PKG
else
  echo "re-run with --install to install binaries" >&2
fi


