#!/bin/bash

SRC_VERSION="1.7.10p7"
SRC_FILENAME="sudo-$SRC_VERSION.tgz"
SRC_FETCH_PATH="http://www.sudo.ws/sudo/dist/sudo-$SRC_VERSION.tar.gz"
SRC_FETCH_METHOD="http"

set -e
if [[ ! -e ../$SRC_FILENAME ]] ; then
    if ! curl -L -s -o "../$SRC_FILENAME" "$SRC_FETCH_PATH" ; then
        die "can't read or download $SRC_FILENAME"
    fi
fi

tar zxf ../$SRC_FILENAME --strip-components 1
./configure --prefix="/usr" --sysconfdir="/etc" --with-env-editor
make
strip sudo

if [[ -d $DESTDIR ]] ; then
  cp sudo $DESTDIR/$PKG
else
  echo "re-run with --install to install binaries" >&2
fi
