#!/bin/bash

TEMPDIR=$BUILDDIR
SRC_FILENAME="flxutils.tgz"
SRC_FETCH_PATH="http://git.formilux.org/?p=dist/src/flxutils.git;a=snapshot;h=41dbee8f5da100d652899ad403c0e2ac43b16f04;sf=tgz"
SRC_FETCH_METHOD="http"

set -e
if [[ ! -e $SRC_FILENAME ]] ; then
    if ! curl -s -o "$SRC_FILENAME" "$SRC_FETCH_PATH" ; then
        die "can't read or download $SRC_FILENAME"
    fi
fi
mkdir -p $BUILDDIR
tar zxf $SRC_FILENAME --strip-components 1 -C $BUILDDIR
( cd $BUILDDIR/flx ; make clean ; make )

if [[ -d $DESTDIR ]] ; then
  cp $BUILDDIR/flx/flx $DESTDIR/
else
  echo "re-run with --install to install binaries" >&2
fi
