#!/bin/bash

SRC_FILENAME="squashfs-$SQUASHFS_VERSION.tgz"
SRC_FETCH_PATH="http://sourceforge.net/projects/squashfs/files/squashfs/squashfs$SQUASHFS_VERSION/squashfs$SQUASHFS_VERSION.tar.gz/download"
SRC_FETCH_METHOD="http"

set -e
if [[ ! -e ../$SRC_FILENAME ]] ; then
    if ! curl -L -s -o "../$SRC_FILENAME" "$SRC_FETCH_PATH" ; then
        die "can't read or download $SRC_FILENAME"
    fi
fi
tar zxf ../$SRC_FILENAME --strip-components 1 -C $BUILDDIR
( cd $BUILDDIR/squashfs-tools ; make )

if [[ -d $DESTDIR ]] ; then
  cp squashfs-tools/mksquashfs $DESTDIR/$PKG
else
  echo "re-run with --install to install binaries" >&2
fi
