#!/bin/bash

SRC_VERSION="3.15"
SRC_FILENAME="module-init-tools-$SRC_VERSION.tgz"
SRC_FETCH_PATH="https://www.kernel.org/pub/linux/utils/kernel/module-init-tools/module-init-tools-$SRC_VERSION.tar.gz"
SRC_FETCH_METHOD="http"

set -e
if [[ ! -e ..$SRC_FILENAME ]] ; then
    if ! curl -L -s -o "../$SRC_FILENAME" "$SRC_FETCH_PATH" ; then
        die "can't read or download $SRC_FILENAME"
    fi
fi
tar zxf ../$SRC_FILENAME --strip-components 1 -C $BUILDDIR
./configure --enable-zlib-dynamic
make depmod
strip build/depmod

if [[ -d $DESTDIR ]] ; then
  cp build/depmod $DESTDIR/$PKG
else
  echo "re-run with --install to install binaries" >&2
fi


